---
title: "Blast to Arabidopsis"
output: html_notebook
---

Quickie annotation by blasting TanOak to Arabidopsis

```{r}
library(tidyverse)
library(org.At.tair.db)
```


```{bash}
cd ../input
wget ftp://ftp.arabidopsis.org/home/tair/Sequences/blast_datasets/TAIR10_blastsets/TAIR10_pep_20110103_representative_gene_model_updated
mv TAIR10_pep_20110103_representative_gene_model_updated TAIR10_pep_20110103_representative_gene_model_updated.fa
```

```{bash, eval=FALSE}
cd ../input
makeblastdb -in TAIR10_pep_20110103_representative_gene_model_updated.fa -dbtype prot
```


```{bash, eval=FALSE}

cd ../output

blastp -query ../input/blast/TanOak.proteins.fa \
  -db ../input/TAIR10_pep_20110103_representative_gene_model_updated.fa \
  -outfmt 10 \
  -evalue 10e-3 \
  -num_threads 3 \
  -culling_limit 2 \
  -max_target_seqs 5 \
  -out TanOakVsA.t.blast_out.csv
```


## Add annotation

annotation data
```{r}
Atblast <- read_csv("../output/TanOakVsA.t.blast_out.csv", col_names = str_split("genes AGI pident length mismatch gapopen qstart qend sstart send evalue bitscore", " ")[[1]])
head(Atblast)
```


```{r}
interpro <- read_tsv("../output/12_21_tanoak_interpro.tsv.gz", col_names = FALSE)
#interpro <- read_tsv("../output/output.iprscan", col_names = FALSE)
head(interpro)
```
```{r}
interpro_clean <- interpro %>% 
  dplyr::select(genes=X1, description=X6 ) %>% 
  unique() %>% 
  na.omit() %>% 
  group_by(genes) %>%
  summarize(interpro.description = str_c(description, collapse="; "))
  
interpro_clean
```

```{r}
annotation <- Atblast %>%
  dplyr::select(genes, AGI, pident, length, evalue, bitscore) %>%
  group_by(genes) %>%
  slice_max(order_by=bitscore, n=1) %>%
  mutate(AGI=str_remove(AGI, "\\.[0-9]"),
         AT.symbol = unlist(as.list(org.At.tairSYMBOL[AGI]))[[1]]) %>%
    right_join(interpro_clean) %>%
  dplyr::select(genes, AT.symbol, AGI, interpro.description, everything()) 

annotation

write_csv(annotation, "../output/annotated_genes.csv.gz")
```



