---
title: "Analyze SnpEffSnps"
output: html_notebook
---

```{r}
library(tidyverse)
library(UpSetR)
datadir <- "~/Library/CloudStorage/GoogleDrive-jnmaloof@ucdavis.edu/Shared drives/TanOak/new_12_2021_assembly/"
```

```{r}
load(file.path(datadir, "SnpEffFilteredTibble.Rdata"))
```

```{r}
head(VRtibble, 200)
```

## Some summaries
Summarize this data

```{r}
table(VRtibble$effect, VRtibble$impact) %>%
  as.data.frame() %>%
  rename(effect=Var1, impact=Var2, freq=Freq) %>%
  pivot_wider(names_from = "impact", values_from = "freq") %>%
  select(effect, HIGH, MODERATE, LOW) %>%
  arrange(desc(HIGH), desc(MODERATE), desc(LOW)) %>%
  write_csv("../output/impact.csv")
```


```{r}
VRtibble %>%
  group_by(impact) %>%
  filter(impact!="LOW",
         !duplicated(snpID)) %>%
  summarize(moderate=sum(impact=="MODERATE"),
            high=sum(impact=="HIGH"),
            total_gene=length(unique(GeneName)))
```

total moderate or high = 
```{r}
VRtibble %>%
  filter(impact!="LOW",
         !duplicated(snpID)) %>%
  nrow()
```

table per tree
```{r}
snps_by_tree <- VRtibble %>%
  filter(impact=="HIGH") %>%
  group_by(sample) %>%
  summarize(Ref=sum(GT=="0/0"),
            Het=sum(GT=="0/1"),
            Alt=sum(GT=="1/1"))

snps_by_tree
  
```

```{r}
snps_by_tree %>%
  pivot_longer(c(Ref, Het, Alt), names_to = "genotype", values_to = "sites") %>%
  ggplot(aes(x=sample, y=sites, fill=genotype)) +
  geom_col() +
  theme(axis.text.x  =element_text(angle=90, hjust=1, vjust=0.5))
  
```
gene table per tree
```{r}
genes_by_tree <- VRtibble %>%
  filter(impact=="HIGH", GT=="1/1") %>%
  group_by(sample) %>%
  filter(!duplicated(GeneName)) %>%
  summarize(Genes_Homozygous_Alt=n())

genes_by_tree
  
```

```{r}
genes_by_tree %>%
  ggplot(aes(x=sample, y=Genes_Homozygous_Alt)) +
  geom_col() +
  theme(axis.text.x  =element_text(angle=90, hjust=1, vjust=0.5))
  
```
upset plot

```{r, fig.width=10}
 VRtibble %>%
  filter(str_detect(sample, "XL", negate = TRUE)) %>%
  filter(impact=="HIGH", GT=="1/1") %>%
  group_by(sample) %>%
  filter(!duplicated(GeneName)) %>%
  select(GeneName, sample) %>%
  table() %>%
  as.data.frame.matrix() %>%
upset(nsets=13, nintersects = 50, order.by = "freq" )
```


## pheno
get the pheno data
```{r}

samples <- unique(VRtibble$sample)

pheno <- read_csv("../input/TanOakResistance.csv") %>%
  mutate(nameMatch=str_replace_all(Tanoak, "-","."),
           nameMatch=str_replace(nameMatch, "SM\\.(52|54)\\.(42|81|97|37)", "\\1.\\2")) %>%
  arrange(Rank_Sorting)
  

pheno

```

missing 
```{r}
pheno.samples <- pheno %>% pull(nameMatch) %>% unique()

samples[! samples %in% pheno.samples]
```


join them
```{r}
VRtibble <- VRtibble %>% inner_join(pheno, by=c("sample"="nameMatch"))
```

Group by SNP and nest so that we can do a Fisher test on each SNP
```{r}
system.time(
  VRtibble <- VRtibble %>% dplyr::select(snpID, sample, GT, Tolerance_Resistance, effect, impact, GeneName, CDSpos_len) %>%
    group_by(snpID) %>%
    nest(data=c(sample, GT, Tolerance_Resistance))
) #16 seconds
head(VRtibble)
```


```{r}
fisherp <- function(data){ #get p value from fisher test
  if(length(unique(data$GT))==1) 
    return(NA) 
  tb <- table(data$GT, data$Tolerance_Resistance)
  fisher.test(tb) %>%
    magrittr::extract("p.value") %>% 
    unlist() %>%
    return()
}
```

```{r}
data <- VRtibble$data[[1]]
```


```{r}
system.time(
test <- VRtibble %>%
  mutate(fisher=map_dbl(data, fisherp))
) # 227 seconds
test %>% arrange(fisher) %>% head(200)
```

```{r}
gene_summary <- test %>%
  group_by(GeneName) %>%
  summarize(min.p=min(fisher), avg.p=mean(fisher), snps=n()) %>%
  arrange(min.p, avg.p, desc(snps))
```


```{r}
gene_summary
```

## get blast

```{r}
header <- c("query",
            "subject",
            "percentID",
            "length",
            "mismatch",
            "gapopen",
            "qstart",
            "qend",
            "sstart",
            "send",
            "evalue",
            "bitscore"
)

blast <- read_csv("../output/TanOakVsA.t.blast_out.csv", col_names = header)

head(blast)
```

```{r}
blast.best <- blast %>% group_by(query) %>%
  filter(row_number(desc(bitscore))==1)
head(blast.best)
```

get annotation.  Download from https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FSubscriber_Data_Releases%2FTAIR_Data_20201231

```{r}
atDesc <- read_tsv("../input/Araport11_functional_descriptions_20201231.txt.gz") %>%
  mutate(name = str_remove(name, "\\..*$")) %>%
  rename_all(funs(str_c("At_", .))) %>%
    filter(!duplicated(At_name)) %>% #not ideal
  select(-At_gene_model_type)
atDesc
```

```{r}
atSymbol <- read_tsv("../input/gene_aliases_20201231.txt.gz") %>%
    rename_all(funs(str_c("At_", .))) %>%
  filter(!duplicated(At_name)) #not ideal
atSymbol
```

```{r}
blast.best <- blast.best %>%
  mutate(AGI = str_remove(subject, "\\..*$")) %>%
  left_join(atSymbol, by = c("AGI" = "At_name")) %>%
  left_join(atDesc, by = c("AGI" = "At_name"))
```

```{r}
gene_summary_ann <- blast.best %>% select(query, subject, percentID, length, starts_with("At_")) %>%
  mutate(query=str_remove(query, "-mRNA-.*")) %>%
  right_join(gene_summary, by= c("query" = "GeneName")) %>%
  select(min.p, avg.p, snps, query, everything())
```


## ADD INTERPRO SCAN ANNOTATION

```{r}
interpro <- read_tsv("../output/12_21_tanoak_interpro.tsv.gz", col_names = FALSE)
interpro
```

```{r}
gene_summary_ann <- interpro %>% 
  dplyr::select(geneID=X1, description=X6 ) %>% 
  mutate(description=str_replace_na(description, "")) %>%
  group_by(geneID) %>%
  summarize(interpro.description = str_c(description, collapse="; ")) %>%
  ungroup() %>%
  mutate(geneID=str_remove(geneID, "-mRNA-.*"),
         interpro.description=str_replace_all(interpro.description, "(; ){2,}", "; "),
         interpro.description=str_remove(interpro.description, "(^; )|(; $)")) %>%
  unique() %>% 
  na.omit() %>% 
  right_join(gene_summary_ann, by=c("geneID"="query")) %>%
  select(geneID, min.p, avg.p, snps, interpro.description, everything())
  
gene_summary_ann
```


```{r}
gene_summary_ann <- gene_summary_ann  %>% ungroup() %>%  arrange(avg.p, desc(snps))
gene_summary_ann   
```

```{r}
write_csv(gene_summary_ann, file="../output/Annotated_SNPeff_Summary.csv")
write_csv(gene_summary_ann, file=file.path(datadir, "Annotated_SNPeff_Summary.csv"))

```

```{r}
gene_summary_ann %>%
  ungroup() %>%
  mutate(avg.fdr = p.adjust(avg.p, method="fdr")) %>%
  select(min.p, avg.p, avg.fdr) %>%
  arrange(avg.fdr)
```

```{r}
gene_summary_ann %>%
  ungroup() %>%
  summarize(genes_min_p_lt_0.05=sum(min.p<0.05, na.rm = TRUE),
          genes_avg_p_lt_0.05=sum(avg.p<0.05, na.rm=TRUE))
```

