---
title: "PCA of SNPs"
output: html_notebook
---

Will make a PCA plot of SNPs, colored by phenotype

```{r}
library(tidyverse)
library(VariantAnnotation)
datadir <- "/Volumes/GoogleDrive/Shared drives/TanOak/"
outdir <- "../output/"
```

```{r}
tab <- TabixFile(file.path(datadir, "cohort.genotyped.snpEff.vcf.bgz"))

tab_seqnames <- seqnamesTabix(tab)

## load contig lengths file 
contig.lengths <- read_csv("../output/contigLengths.csv")

contig.lengths_tab <- contig.lengths %>%
  filter(name %in% tab_seqnames)
```

```{r}
## get pheno data
pheno <- read_csv("../input/TanOakResistance.csv") %>%
  mutate(sampleID=str_replace_all(Tanoak, "-","."),
         sampleID=str_replace(sampleID, "SM\\.(52|54)\\.(42|81|97|37)", "\\1.\\2")) %>%
  arrange(Rank_Sorting)
```

select a subset of scaffolds to load
```{r}
set.seed(321)
contigs.subset <- sample(1:nrow(contig.lengths_tab), size = 200)
```


```{r}
vcf <-  readVcf(tab, 
                param=GRanges(
                  seqnames = contig.lengths_tab$name[contigs.subset],
                  ranges = IRanges(
                    start = 1,
                    end=contig.lengths_tab$length[contigs.subset])))
```


```{r}
# filter it
vcf <- vcf[rowRanges(vcf)$QUAL > 50 &
             sapply(info(vcf)$AC, length) == 1 & #stick with biallelic SNPs for now
             info(vcf)$AN == 28] # require complete genotype info for now 
```


```{r}
mat <- genotypeToSnpMatrix(vcf)
mat3 <- as(mat$genotypes, "numeric")
dim(mat3)
mat3[1:10, 1:10]
mat4 <- mat3[,apply(mat3, 2, function(x) !any(is.na(x)))]
dim(mat4)
```

PCAs
```{r}
geno.pca <- prcomp(mat4, rank.=10)
```

```{r}
pcvar <- geno.pca$sdev^2 # square std dev to get variance
pcvar.pct <- tibble(pctvar=pcvar/sum(pcvar) * 100,
                    PC=1:length(pcvar))
pcvar.pct %>% ggplot(aes(x=PC,y=pctvar)) +
  geom_col()

```

```{r}
rownames(mat4)

```

make PCA frame for plotting
```{r}
PCs <- geno.pca$x %>%
  as.data.frame() %>%
  rownames_to_column("sampleID") %>%
  left_join(pheno)
PCs
```

```{r}
PCs %>%
  ggplot(aes(x=PC1, y=PC2, color=Tolerance_Resistance, label=sampleID)) +
  geom_text() 
```

```{r}
for(i in 2:10) {
  PC <- as.name(str_c("PC", i))
  print( PCs %>% ggplot(aes(x=PC1, y= !!PC, color=Tolerance_Resistance, label=sampleID)) +
  geom_text()  )
}
```



```{r}
pdf("../output/PCAplots.pdf")
for(i in 2:10) {
  PC <- as.name(str_c("PC", i))
  print( PCs %>% ggplot(aes(x=PC1, y= !!PC, color=Tolerance_Resistance, label=sampleID)) +
  geom_text()  )
}
dev.off()
```


