---
title: "BLAST Tanoak OAK"
author: "Julin Maloof"
date: "01/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Goal is an all by all BLAST at the gene level in preparation for doing dN/dS.  (want to ID orthologs)

## Oak Seqs

```{r}
if(!file.exists("../input/blast/Qrob_PM1N_CDS_nt_20161004.fa.gz")) {
  download.file(
    "https://urgi.versailles.inra.fr/download/oak/Qrob_PM1N_CDS_nt_20161004.fa.gz",
    destfile = "../input/blast/Qrob_PM1N_CDS_nt_20161004.fa.gz")
  download.file(
    "https://urgi.versailles.inra.fr/download/oak/Qrob_PM1N_CDS_aa_20161004.fa.gz",
    destfile = "../input/blast/Qrob_PM1N_CDS_aa_20161004.fa.gz")
}
```

## create fasta files
```{bash, eval=FALSE}
 gffread -g PanGenome_ONT_pilon.purge.dedup90.drop2k.mergeN.fasta -x 12_21_tanoak_CDS_v2.fa -y 12_21_tanoak_aav_2.fa v4draft.maker.repeatlib.noseq.gff
```


## make blast databases

```{bash, eval=FALSE}
cd ../input/blast

gunzip Qrob_PM1N_CDS_nt_20161004.fa.gz
makeblastdb -in Qrob_PM1N_CDS_nt_20161004.fa -dbtype nucl

gunzip Qrob_PM1N_CDS_aa_20161004.fa.gz
makeblastdb -in Qrob_PM1N_CDS_aa_20161004.fa -dbtype prot

makeblastdb -in 12_21_tanoak_CDS.fa -dbtype nucl

makeblastdb -in 12_21_tanoak_aa.fa -dbtype prot
```

## nucleotide blast

Tanoak to Oak

```{bash}
cd ../input/blast
time blastn -query 12_21_tanoak_CDS.fa \
  -db Qrob_PM1N_CDS_nt_20161004.fa \
  -strand plus \
  -task dc-megablast \
  -outfmt '10 std qlen slen' \
  -max_target_seqs 5 \
  -max_hsps 1 \
  -evalue 10e-4 \
  -num_threads 3 \
  -out ../../output/TanOak_to_Oak_dc-megablast.csv
```

Oak to Tanoak

```{bash}
cd ../input/blast
time blastn -query Qrob_PM1N_CDS_nt_20161004.fa \
  -db  12_21_tanoak_CDS.fa \
  -strand plus \
  -task dc-megablast \
  -outfmt '10 std qlen slen' \
  -max_target_seqs 5 \
  -max_hsps 1 \
  -evalue 10e-4 \
  -num_threads 3 \
  -out ../../output/Oak_to_Tanoak_dc-megablast.csv
```

## protein blast

Tanoak to Oak

```{bash}
cd ../input/blast
time blastp -query 12_21_tanoak_aa.fa \
  -db Qrob_PM1N_CDS_aa_20161004.fa \
  -outfmt '10 std qlen slen' \
  -max_target_seqs 5 \
  -max_hsps 1 \
  -evalue 10e-4 \
  -num_threads 3 \
  -out ../../output/TanOak_to_Oak_blastp.csv
```

Oak to Tanoak

```{bash}
cd ../input/blast
time blastp -query Qrob_PM1N_CDS_aa_20161004.fa \
  -db 12_21_tanoak_aa.fa  \
  -outfmt '10 std qlen slen' \
  -max_target_seqs 5 \
  -max_hsps 1 \
  -evalue 10e-4 \
  -num_threads 3 \
  -out ../../output/Oak_to_Tanoak_blastp.csv
```

